### PR TITLE
Merge Development to Master

### PR DESCRIPTION
**Pull request by Nuhvi**

### CODE REVIEW

**Review by bellom — CHANGES_REQUESTED** [review]
Hi @Nazeh ,

Good job. Here is the checklist for your project.
- To consider the project 'complete' it must satisfy the following points:
## General
- [x] The project has a descriptive README.md
## Navigation bar
* [x] It should use a linear gradient as background color
* [ ] It should be made of nine different buttons with the Apple logo on the leftmost section and a search field on the rightmost section
* [ ] It should be within the `<main>` tag
## Search field
-  [ ] The search field should be an `<input>` HTML tag with the *focus* effect enabled
## Background
-  [ ] The main content should be wrapped around `<main>` tags and have an image set as background
## Main Content Links
* [ ] There should be three links
* [ ] Each link is an `<div>` HTML tag, with a `<a>` tag inside it.
* [ ] The `<a>` tag inside the `<div>` tag should use an image as background -- \[ \] The text on the original page is actually an image
## Bottom
-  [ ] It has buttons positioned either as *floats* or *display flex*
## Footer 
* [x] It should be wrapped by `<footer>` tags
* [ ] The top part is made of four `<a>` tags with `` tags inside it
* [ ] The `<a>` tags should use an image as a background
* [ ] The bottom part should include links like copyright, terms of use, and privacy policy

**Note: Always Compare your web page to the original website, it will really help, your web page looks a little bit off, see for yourself** :point_down:

image

**After fixing the _**unchecked**_ issues and the validation errors please send another request to re-review this project.**

Tips:
For every HTML/CSS projects please check your files with the W3 Validator and the CSS Linter

Thanks 🙏

**Comment by bellom** [comment]
I strongly doesn't understand your act of merging to master without an approval.
Can you please explain ?

**Comment by Nuhvi** [comment]
> I strongly doesn't understand your act of merging to master without an approval.
> Can you please explain ?

I didn't merge!!

I merely closed the pull request until I make changes and submit a new one!

**Comment by bellom** [comment]
No, kindly don't do that next time, you don't create another PR, you are to use one PR all through the code review.
Thanks

**Comment by Nuhvi** [comment]
> No, kindly don't do that next time, you don't create another PR, you are to use one PR all through the code review.
> Thanks

I reopened it.
However, in the raw.githack, unlike with my live server preview all the relative local links to assets as background images and reset.css is not working, do you know how I can fix this?

**Comment by bellom** [comment]
I will message you on slack now 
You can also message me with handle - @sean bellom

**Review by bellom — APPROVED** [review]
Hi @Nazeh , 
## Congratulation, Amazing Job :+1: 
Go ahead and merge to master.

**Pull request merged**
